### Importação do Pytorch e do Numpy

In [1]:
import torch
import numpy as np

### Conversão de lista para tensor e tensor para array numpy

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data) # data: int64 | Tensor(data) # float32
print(x_data)
print("dtype: ", x_data.dtype)

tensor([[1, 2],
        [3, 4]])
dtype:  torch.int64


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### Inicializando tensores

- torch.ones_like: pode receber um tensor como entrada e novo tensor será gerado com o formato do tensor de entrada.

- torch.ones: não permite receber um tensor como entrada e seu 1º argumento é o formato.

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 



In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.5482, 0.1115],
        [0.7924, 0.5252]]) 



In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6735, 0.4892, 0.8475],
        [0.7509, 0.3327, 0.3504]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Exibição das informações dos tensores

In [7]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}") # formato: linhas e/ou colunas
print(f"Datatype of tensor: {tensor.dtype}") # tipo de dado
print(f"Device tensor is stored on: {tensor.device}") # dispositivo de armazenamento

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Troca de dispositivo de processamento

In [8]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")
else:
  print(tensor.device)

cpu


### Técnica de fatiamento

In [9]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[..., -1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


### Exercício

In [10]:
tns = torch.randn(9,12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


In [11]:
data1 = [[1,2], [3,4]]
data2 = [[5,6],[7,8]]
data3 = [[9,10], [11,12]]

tns1 = torch.tensor(data1)
tns2 = torch.tensor(data2)
tns3 = torch.tensor(data3)

tns_stack = torch.stack([tns1, tns2, tns3]) # concatena uma sequência de tensores
print(tns_stack)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


In [12]:
t1_t2 = torch.mm(tns1,tns2)
print(t1_t2)

tensor([[19, 22],
        [43, 50]])


In [13]:
t1_t2_t3 = torch.mm(t1_t2, tns3)
print(t1_t2_t3)

tensor([[ 413,  454],
        [ 937, 1030]])


In [14]:
x = torch.randn(2,3)
print(x)

tensor([[ 0.4644,  1.2214, -0.6420],
        [-0.6666,  0.1358, -0.7721]])


### Concatenação de Tensores

In [15]:
# dim = 0 -> tensores concatenados na 1D (linha)
x_cat = torch.cat((x,x,x),0)
print(x_cat) # shape(6,3)

# dim = 1 -> tensores concatenados na 2D (coluna)
x_cat_n = torch.cat((x, x, x), 1)
print(x_cat_n) # shape(2,9)

# para tensores 3D a dimensão pode ser: 0, 1, 2
# para tensores multidimensionais a dimensão pode assumir qualquer valor

# o argumento out é indicado quando temos um tensor novo (vazio)
# para armazenar o novo tensor retornado pelo método

# para criar um tensor vazio temos o método: torch.empty(nl, nc)

tensor([[ 0.4644,  1.2214, -0.6420],
        [-0.6666,  0.1358, -0.7721],
        [ 0.4644,  1.2214, -0.6420],
        [-0.6666,  0.1358, -0.7721],
        [ 0.4644,  1.2214, -0.6420],
        [-0.6666,  0.1358, -0.7721]])
tensor([[ 0.4644,  1.2214, -0.6420,  0.4644,  1.2214, -0.6420,  0.4644,  1.2214,
         -0.6420],
        [-0.6666,  0.1358, -0.7721, -0.6666,  0.1358, -0.7721, -0.6666,  0.1358,
         -0.7721]])


### Divisão de tensores

- split: tamanhos
- chunks: pedaços
- tensor_split: subtensores

In [16]:
tensor = torch.arange(10)
print(tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


**Método split**

Controle sobre o tamanho dos pedaços

In [17]:
# c / chunk terá tamanho igual, exceto o último se não for divisível pelo tamanho (split_size)
chunks = torch.split(tensor,3)
for i, chunk in enumerate(chunks):
  print(f"Chunk {i}: {chunk} e {chunk.size()}")

Chunk 0: tensor([0, 1, 2]) e torch.Size([3])
Chunk 1: tensor([3, 4, 5]) e torch.Size([3])
Chunk 2: tensor([6, 7, 8]) e torch.Size([3])
Chunk 3: tensor([9]) e torch.Size([1])


In [18]:
# c / chunk terá tamanho diferente (sections)
chunks = torch.split(tensor,[4, 2, 4])
for i, chunk in enumerate(chunks):
  print(f"Chunk {i}: {chunk} e {chunk.size()}")

Chunk 0: tensor([0, 1, 2, 3]) e torch.Size([4])
Chunk 1: tensor([4, 5]) e torch.Size([2])
Chunk 2: tensor([6, 7, 8, 9]) e torch.Size([4])


**Método chunk**

Controle sobre a quantidade de pedaços. Não aceita lista ou tupla como argumento

In [19]:
# dividiu o tensor em 6 partes iguais
torch.arange(12).chunk(6)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10, 11]))

In [20]:
# dividiu o tensor em 5 partes iguais e 1 diferente
torch.arange(11).chunk(6)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10]))

**Método torch.tensor_split**

Controle sobre a quantidade de pedaços, contudo aceita lista ou tupla sendo que diferente do torch.split a lista ou a tupla receberá em qual índice inicia o corte respeitando a regra:
- antes do índice especificado
- entre os índices especifiados
- após o índice especificado
- exemplo: (1,6)
    - antes do índice 1
    - entre índice 1 a 6
    - após o índice 6

No caso do torch.split, a lista ou a tupla especifica o tamanho de cada pedaço

In [21]:
x = torch.arange(8).reshape(4,2)
torch.tensor_split(x, 3)

# torch.tensor_split(tns, index_or_sections, dim)
# index_or_sections é diferente de split_size_or_section

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5]]),
 tensor([[6, 7]]))

In [22]:
torch.tensor_split(x, 3, 1)

(tensor([[0],
         [2],
         [4],
         [6]]),
 tensor([[1],
         [3],
         [5],
         [7]]),
 tensor([], size=(4, 0), dtype=torch.int64))

### Operações aritméticas

- @ : calcula o produto interno. Multiplica cada elemento do tensor com elemento do outro tensor e soma todos  os resultados.

- T: faz a transposição em tensores com mais de 1D: (l x c) -> (c x l)

- torch.matmul: faz multiplicação entre dois tensores

- torch.mul: faz multplicação entre dois tensores ou um tensor e um número

**Multiplicação com "@"**

In [23]:
y = torch.arange(10)
y_t = y @ y
print(y_t)

tensor(285)


In [24]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

x_t = x @ x.T

print(x_t)

tensor([[14, 32],
        [32, 77]])


**Multiplicação com matmul**



In [25]:
x_mt = x.matmul(x.T)
print(x_mt)

tensor([[14, 32],
        [32, 77]])


**Multiplicação com mul**

O método torch.mul aceita dois tensores podendo um deles ser transposto;

O método tensor.mul não aceita tensores transpostos, sendo que nesse exemplo o método acessa diretamente o tensor, diferente do método anterior.

O método mul permite multiplicar o tensor por um número.

Quando passamos um tensor transposto o pytorch faz um broadcasting transformando virtualmente o tensor transposto no tensor original.


Para evitar comportamento inesperado ou erro use o método **mul** com tensores com o mesmo formato.

In [26]:
# comportamento inesperado -> realizou um broadcasting ou dará um erro
# x_ml = torch.mul(x,x.T)
# print(x_ml)

In [27]:
# melhor maneira de usar o método mul ou torch.mul
x_ml = x.mul(x)
print(x_ml)

tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [28]:
# x_t = x.T
# x_ml = x.mul(x_t)
# print(x_ml)

### Produto Escalar (inteno) x Produto de Matrizes

- Produto escalar retorna apenas uma valor, é a soma do produto de cada elemento do vetor.

- Produto de Matrizes retorna uma nova matriz com o resultado do produto de cada elemento do vetor.

### Visualização de Tensor (View)

Altera o formato de um tensor sem alterar seus dados, sendo equivalente ao reshape, mas o reshape pode retornar um tensor diferente. Em caso de tensor contíguo o reshape cria uma cópia, enquanto que view lança um erro.

O view não cria uma cópia dos dados, ele cria um novo tensor que aponta para a mesma memória.

Número total de elementos deve ser igual: a multiplicação das novas dimensões deve ser igual ao número total de elementos do tensor original. Se tenho um tensor de 6 elementos, a multiplicação das dimensões deve resultar em 6: 3 x2 ou 2 x 3.

O tensor contíguo é aquele os dados estã armazenados em único bloco contínuo de memória; não contíguo é aquele em que os dados estão armazenados em blocos diferentes na memória devido a operações de slicing (fatiamento) ou de transposição.

Em caso de um tensor não contíguo, use o método *contíguos()* para criar uma cópia contígua do tensor.

In [29]:
x = torch.randn(4,4)
x.size()
x

tensor([[ 0.3877, -1.0979, -0.1212,  0.3867],
        [ 0.9955,  1.8213, -1.4810,  0.0313],
        [ 0.0887,  1.0984, -1.3427, -0.4186],
        [ 1.1492,  0.0814, -0.3661,  1.6522]])

In [30]:
y = x.view(16)
print(y)
print(y.size())

tensor([ 0.3877, -1.0979, -0.1212,  0.3867,  0.9955,  1.8213, -1.4810,  0.0313,
         0.0887,  1.0984, -1.3427, -0.4186,  1.1492,  0.0814, -0.3661,  1.6522])
torch.Size([16])


In [31]:
z = x.view(-1, 8) # -1 é uma dimensão coringa que será dada com base nas dimensões anteriores
print(z)
print(z.size())

tensor([[ 0.3877, -1.0979, -0.1212,  0.3867,  0.9955,  1.8213, -1.4810,  0.0313],
        [ 0.0887,  1.0984, -1.3427, -0.4186,  1.1492,  0.0814, -0.3661,  1.6522]])
torch.Size([2, 8])


In [36]:
h = x.reshape(-1,8)
print(h.size())
print(h)

torch.Size([2, 8])
tensor([[ 0.3877, -1.0979, -0.1212,  0.3867,  0.9955,  1.8213, -1.4810,  0.0313],
        [ 0.0887,  1.0984, -1.3427, -0.4186,  1.1492,  0.0814, -0.3661,  1.6522]])
